### ISSUE TITLE
Headlines approximation, instead of files approximation

### ISSUE THREAD

**Issue by Ypot** [hrs/docsim.el#7]
Is it possible to search inside buffers, where each headline corresponds to a note.

I would propose: docsim-search-agenda

**Comment by hrs** [comment]
Hmm, sorry, but I don't think we're going to do that right now. The underlying [`docsim`](https://github.com/hrs/docsim) tool doesn't parse Org files differently from any other kind of text file, and changing it to do so would be a *huge* change. Plus most tools that work on top of Org already use files as their "fundamental unit" (like `denote`, `org-roam`, or `deft`), so this seems consistent with those.
